apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hextris.fullname" . }}-nginx
  labels:
    {{- include "hextris.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
