apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    app: hextris-ci
spec:
  serviceAccountName: default
  containers:
  - name: docker
    image: docker:24-dind
    args:
    - --storage-driver=overlay2
    - --tls=false
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph
      mountPath: /var/lib/docker
    readinessProbe:
      exec:
        command:
        - docker
        - version
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm:3.13.0
    command:
    - cat
    tty: true
  volumes:
  - name: docker-graph
    emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
