apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    app: hextris-ci
spec:
  serviceAccountName: default
  containers:
  - name: docker
    image: docker:24-dind
    command:
    - sh
    - -c
    - |
      dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --tls=false &
      sleep 10
      tail -f /dev/null
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm:3.13.0
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
