apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    app: hextris-ci
spec:
  serviceAccountName: default
  containers:
  - name: docker
    image: docker:24-dind
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: kubectl
    image: bitnami/kubectl:1.28
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  - name: helm
    image: alpine/helm:3.13.0
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
