apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    app: hextris-ci
spec:
  serviceAccountName: default
  containers:
  - name: dind
    image: docker:24-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    - name: DOCKER_DRIVER
      value: overlay2
    ports:
    - containerPort: 2375
    volumeMounts:
    - name: docker-graph
      mountPath: /var/lib/docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: docker
    image: docker:24-cli
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm:3.13.0
    command:
    - cat
    tty: true
  volumes:
  - name: docker-graph
    emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
