apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    app: hextris-ci
spec:
  serviceAccountName: default
  containers:
  - name: docker
    image: docker:24-dind
    command:
    - sh
    - -c
    - |
      dockerd-entrypoint.sh &
      sleep 10
      cat
    tty: true
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - name: docker-graph
      mountPath: /var/lib/docker
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  - name: helm
    image: alpine/helm:3.13.0
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  volumes:
  - name: docker-graph
    emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
